# Generated by Django 5.1.7 on 2025-03-16 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('caja', 'Caja')], default='caja', max_length=20),
        ),
    ]
