# Generated by Django 5.1.7 on 2025-03-18 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detalleCaja', '0001_initial'),
        ('transacciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecaja',
            name='transaccion_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transacciones.transaccion'),
        ),
    ]
